name: Test & Publish

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint lib/
        run: yarn lint

  publish-npm:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with ADMIN_TOKEN
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v4
        with:
           token: ${{ secrets.ADMIN_TOKEN }}

      - name: Checkout code
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Create Release
        env:
          token: ${{ secrets.ADMIN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npx auto shipit
